server:
  port: 8082

spring:
  application:
    name: user-service
  profiles:
    active: dev # Default run on local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}