#Server Properties
server.port=8082
spring.application.name=user-service

#JWT Config
jwt.secret=bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5MTYwOTIwMjYwMA==
jwt.expiration=7200000

## Database Properties
spring.datasource.url = jdbc:postgresql://localhost:5432/user-access-management?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username = postgres
spring.datasource.password = P@ssw0rd

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

# Initialize data
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Show SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true