#Server Properties
server.port=8081
spring.application.name=auth-service

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

# Initialize data
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# Show SQL queries
spring.jpa.properties.hibernate.format_sql=true
